### ISSUE TITLE
Rounding problem inside built-in functions

### ISSUE THREAD

**Issue by ScorpioT1000** [brick/math#13]
```php
BigDecimal::of(microtime(true))->multipliedBy('1000')->toBigInteger()
```

throws "Rounding is necessary to represent the result of the operation at this scale."

**Comment by ScorpioT1000** [comment]
Workaround is:

```php
BigDecimal::of(microtime(true))
                ->multipliedBy('1000')
                ->toScale(0, RoundingMode::DOWN)    
                ->toBigInteger()
```

But I think the function toBigInteger must do it by itself

**Comment by BenMorel** [comment]
Hi, this is not a bug, but a feature.

By design, the [toBigInteger()](https://github.com/brick/math/blob/0.7.1/src/BigNumber.php#L334-L341) method explicitly throws an exception if the current number cannot be converted to a `BigInteger` **without rounding**.

Implicicit rounding would create more issues than it would solve.

Your code is not a workaround, it's the proper way to explicitly tell the library that **the number needs to be rounded** before converting it!

**Comment by jkuchar** [comment]
Strict explicit rounding is probably the most useful feature of this library.

**Comment by julian-sawicki-skrepr** [comment]
**Reproducing**

Let's create the decimal `12.5`. 

```
$bigDecimal = BigDecimal::zero()->plus(100)->dividedBy(8, 2);
var_dump($bigDecimal);exit;
```
Output: 

```
object(Brick\Math\BigDecimal)#11269 (2) {
  ["value":"Brick\Math\BigDecimal":private]=>
  string(4) "1250"
  ["scale":"Brick\Math\BigDecimal":private]=>
  int(2)
}
```

Now let's create the error: `Rounding is necessary to represent the result of the operation at this scale.`. 

```
$bigDecimal = BigDecimal::zero()->plus(100)->dividedBy(8, 2);
$int = $bigDecimal->toInt();
var_dump($int);exit;
```

Now let's fix the error: `Rounding is necessary to represent the result of the operation at this scale.` by introducing `toScale(0, RoundingMode::HALF_UP)`. 

```
$bigDecimal = BigDecimal::zero()->plus(100)->dividedBy(8, 2);
$int = $bigDecimal->toScale(0, RoundingMode::HALF_UP)->toInt();
var_dump($int);exit;
```

Output: 

`int(13)`
