### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by c33s** [brick/math#50]
would be nice to have a changelog mainly for seeing breaking changes. 

mainly for quickly see if an upgrade of this lib is possible (https://github.com/mgrajcarek/uuid-shortener/issues/13)

**Comment by BenMorel** [comment]
Hi, the [releases](https://github.com/brick/math/releases) are the changelog, and each `0.x.0` version details the breaking changes to be aware of. Is this enough? Does a changelog file provides something that's missing here?

**Comment by c33s** [comment]
i personally think that it would be handy to have a `CHANGELOG.md`, for me it is the first location where i look for (breaking) changes.
what do you think of duplicating the info from the releases page in the `CHANGELOG.md` or if you don't want that put a link to the releases page (mainly add the comment you wrote here into a changelog file)?

**Comment by BenMorel** [comment]
@c33s Changelog added! 🎉

https://github.com/brick/math/blob/master/CHANGELOG.md

In addition to being more user-friendly, I can see the value in keeping a changelog file now: it allows me to commit unreleased changes to the changelog as they happen, instead of having to create and maintain a draft release while I perform changes, or having to go through the commit history before a tagging a release to craft a changelog entry.

For anyone interested, I've created a quick script that creates a `CHANGELOG.md` file for any repo, using the GitHub API:

https://gist.github.com/BenMorel/bd2ff5ea3b3eb7cfd0efad6731bbb8bc
